/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bus.FunctionAction;
import dto.Functions;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phong
 */
public class FunctionIFrm extends javax.swing.JInternalFrame {

    /**
     * Creates new form FunctionIFrm
     */
    FunctionAction functions;

    public FunctionIFrm() {
        initComponents();
        functions = new FunctionAction();
        loadTable(functions.readAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnFunction = new javax.swing.JScrollPane();
        tblFunction = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDes = new javax.swing.JTextArea();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setClosable(true);
        setTitle("Functions");

        tblFunction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFunction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFunctionMouseClicked(evt);
            }
        });
        spnFunction.setViewportView(tblFunction);

        jLabel1.setText("Name");

        jLabel2.setText("Description");

        txtDes.setColumns(20);
        txtDes.setRows(5);
        jScrollPane2.setViewportView(txtDes);

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/hospital-symbol.png"))); // NOI18N
        btnCreate.setText("Create");

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/tick-mark.png"))); // NOI18N
        btnUpdate.setText("Update");

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/delete-cross.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnFunction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addComponent(jScrollPane2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spnFunction, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(1, 1, 1)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFunctionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFunctionMouseClicked
        // TODO add your handling code here:
        int row = tblFunction.getSelectedRow();
        txtName.setText((String) tblFunction.getValueAt(row, 0));
        txtDes.setText((String) tblFunction.getValueAt(row, 1));
    }//GEN-LAST:event_tblFunctionMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = tblFunction.getSelectedRow();
        if (row != -1) {
            String name = txtName.getText().trim();
            String des = txtDes.getText().trim();
            int id = functions.readByNameFunction(name).getId();
            if (functions.update(new Functions(id, name, des)) != null) {
                JOptionPane.showMessageDialog(this, "Success");
                txtName.setText("");
                txtDes.setText("");
                loadTable(functions.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Fail");
                txtName.setText("");
                txtDes.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select function to update");
            txtName.setText("");
            txtDes.setText("");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText().trim();
        String des = txtDes.getText().trim();
        if (name.length() != 0) {
            if (functions.readByNameFunction(name) == null) {
                if (functions.create(new Functions(name, des)) != null) {
                    JOptionPane.showMessageDialog(this, "Success");
                    txtName.setText("");
                    txtDes.setText("");
                    loadTable(functions.readAll());
                } else {
                    JOptionPane.showMessageDialog(this, "Fail");
                    txtName.setText("");
                    txtDes.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Function existed");
                txtName.setText("");
                txtDes.setText("");
            }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblFunction.getSelectedRow();
        if (row != -1) {
            int id = functions.readByNameFunction(txtName.getText()).getId();
            if (functions.delete(id)) {
                JOptionPane.showMessageDialog(this, "Success");
                txtName.setText("");
                txtDes.setText("");
                loadTable(functions.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Fail");
                txtName.setText("");
                txtDes.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select function to delete");
            txtName.setText("");
            txtDes.setText("");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane spnFunction;
    private javax.swing.JTable tblFunction;
    private javax.swing.JTextArea txtDes;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void loadTable(List<Functions> readAll) {
        Vector cols = new Vector();
        cols.add("Name");
        cols.add("Description");

        Vector rows = new Vector();
        for (Functions f : readAll) {
            Vector row = new Vector();
            row.add(f.getName());
            row.add(f.getDes());
            rows.add(row);
        }

        tblFunction.setModel(new DefaultTableModel(rows, cols));
        tblFunction.updateUI();
        spnFunction.setViewportView(this.tblFunction);
    }
}
