/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bus.BillAction;
import bus.InvoiceidAction;
import dao.UsersDAO;
import dto.BillsDTO;
import dto.InvoiceidDTO;
import dto.Users;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thien
 */
public class pnlBillHistory extends javax.swing.JPanel {

    /**
     * Creates new form pnlBillHistory
     */
    BillAction bill = null;
    InvoiceidAction invoi = null;
    Users user = null;
    UsersDAO users = null;

    public pnlBillHistory() {
        initComponents();
    }

    public pnlBillHistory(Users u) {
        initComponents();
        user = u;
        invoi = new InvoiceidAction();
        bill = new BillAction();
        users = new UsersDAO();
        loadTable(invoi.readAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnFilter = new javax.swing.JButton();
        lblTo = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        txtFrom = new com.toedter.calendar.JDateChooser();
        txtTo = new com.toedter.calendar.JDateChooser();
        spnHistoryBill = new javax.swing.JScrollPane();
        tblHistoryBill = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnFilter.setText("Filter");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        lblTo.setText("To");

        lblFrom.setText("From");

        txtFrom.setDateFormatString("dd/MM/yyyy");

        txtTo.setDateFormatString("dd/MM/yyyy");

        tblHistoryBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spnHistoryBill.setViewportView(tblHistoryBill);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jButton2.setText("Seacrh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 260, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addComponent(spnHistoryBill, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFrom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFilter))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFrom)
                    .addComponent(btnFilter)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spnHistoryBill, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainFrm mf = new MainFrm(user);
        mf.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        try {
            Date from = txtFrom.getDate();
            Date to = txtTo.getDate();
            if (from != null && to != null) {
                from = new SimpleDateFormat("dd/MM/yyyy").parse(new SimpleDateFormat("dd/MM/yyyy").format(from));
                to = new SimpleDateFormat("dd/MM/yyyy").parse(new SimpleDateFormat("dd/MM/yyyy").format(to));
                loadTable(invoi.readByDate(from, to));
            } else {
                JOptionPane.showMessageDialog(this, "Select from and to");
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Select day from and to");
        }
    }//GEN-LAST:event_btnFilterActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String name = txtSearch.getText().trim();
        if ((users.readByName(name)) != null) {
            if (invoi.readByUsersId(users.readByName(name).getId()) != null) {
                loadTable(invoi.readByUsersId(users.readByName(name).getId()));
            } else {
                JOptionPane.showMessageDialog(this, "Find not see!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Find not see!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JScrollPane spnHistoryBill;
    private javax.swing.JTable tblHistoryBill;
    private com.toedter.calendar.JDateChooser txtFrom;
    private javax.swing.JTextField txtSearch;
    private com.toedter.calendar.JDateChooser txtTo;
    // End of variables declaration//GEN-END:variables
private void loadTable(List<InvoiceidDTO> readAll) {
        Vector cols = new Vector();
        cols.add("ID");
        cols.add("Users");
        cols.add("Date");
        cols.add("Price");
        cols.add("CustomerId");
        cols.add("CourseId");

        Vector rows = new Vector();
        for (InvoiceidDTO i : readAll) {
            Vector row = new Vector();
            row.add(i.getId());
            row.add(users.readById(i.getUserid()).getUsername());
            row.add(new SimpleDateFormat("dd/MM/yyyy").format(i.getDatetime()));
            row.add(i.getTotal());
            for (BillsDTO j : bill.readAll()) {
                if (j.getInvoiceid() == i.getId()) {
                    row.add(j.getCustomerid());
                    row.add(j.getCourseid());
                    break;
                }
            }
            rows.add(row);
        }

        tblHistoryBill.setModel(new DefaultTableModel(rows, cols));
        tblHistoryBill.updateUI();
        spnHistoryBill.setViewportView(this.tblHistoryBill);
    }
}
