/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author thien
 */
public class pnlFunctionRole extends javax.swing.JPanel {

    /**
     * Creates new form pnlFunctionRole
     */
    public pnlFunctionRole() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnFunction = new javax.swing.JScrollPane();
        tblFunction = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        spnFunctionRole = new javax.swing.JScrollPane();
        tblFunctionRole = new javax.swing.JTable();

        tblFunction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spnFunction.setViewportView(tblFunction);

        jLabel1.setText("Role");

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/hospital-symbol.png"))); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/tick-mark.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblFunctionRole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFunctionRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFunctionRoleMouseClicked(evt);
            }
        });
        spnFunctionRole.setViewportView(tblFunctionRole);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnFunctionRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(spnFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCreate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(spnFunctionRole, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spnFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        List<Integer> listFunctionCreate = new ArrayList<>();
        int size = tblFunction.getModel().getRowCount();
        for (int i = 0; i < size; i++) {
            if ((Boolean) tblFunction.getValueAt(i, 0)) {
                listFunctionCreate.add(functions.readByNameFunction((String) tblFunction.getValueAt(i, 1)).getId());
            }
        }
        int roleid = roles.readByName((String) cmbRole.getSelectedItem()).getId();
        if (listFunctionCreate.size() != 0) {
            if (fr.readByRole(roleid).getFunctions().size() == 0) {
                if (fr.create(new FunctionRoles(roleid, listFunctionCreate)) != null) {
                    JOptionPane.showMessageDialog(this, "Success");
                    loadTable(fr.readAll());
                    loadList(functions.readAll());
                    loadCombobox(roles.readAll());
                } else {
                    JOptionPane.showMessageDialog(this, "Fail");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Role existed");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select at least one function");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (tblFunctionRole.getSelectedRow() != -1) {
            int roleid = roles.readByName((String) cmbRole.getSelectedItem()).getId();
            List<Integer> listFunction = fr.readByRole(roleid).getFunctions();
            int listfunctionsize = listFunction.size();
            List<Integer> listFunctionCreate = new ArrayList<>();
            int listCreatesize = tblFunction.getModel().getRowCount();

            for (int i = 0; i < listCreatesize; i++) {
                if ((Boolean) tblFunction.getValueAt(i, 0)) {
                    listFunctionCreate.add(functions.readByNameFunction((String) tblFunction.getValueAt(i, 1)).getId());
                }
            }

            boolean flag = false;
            List<Integer> create = new ArrayList<>();
            for (Integer i : listFunctionCreate) {
                if (!listFunction.contains(i)) {
                    create.add(i);
                }
            }

            if (fr.create(new FunctionRoles(roleid, create)) != null) {
                flag = true;
            };

            for (Integer i : listFunction) {
                if (!listFunctionCreate.contains(i)) {
                    fr.delete(roleid, i);
                    flag = true;
                }
            }

            if (flag) {
                JOptionPane.showMessageDialog(this, "Success");
                loadTable(fr.readAll());
                loadList(functions.readAll());
                loadCombobox(roles.readAll());
            } else {
                JOptionPane.showMessageDialog(this, "Fail");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select role to update");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainFrm mf = new MainFrm(user);
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblFunctionRoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFunctionRoleMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        loadList(functions.readAll());
        int row = tblFunctionRole.getSelectedRow();
        String rolename = (String) tblFunctionRole.getValueAt(row, 0);
        int roleid = roles.readByName(rolename).getId();
        List<Integer> functionlist = fr.readByRole(roleid).getFunctions();
        DefaultTableModel tm = (DefaultTableModel) tblFunction.getModel();
        int size = tblFunction.getModel().getRowCount();
        for (int i = 0; i < size; i++) {
            if (functionlist.contains(functions.readByNameFunction((String) tblFunction.getValueAt(i, 1)).getId())) {
                tm.setValueAt(true, i, 0);
            }
        }
        tblFunction.setModel(tm);
        cmbRole.setSelectedItem(rolename);
    }//GEN-LAST:event_tblFunctionRoleMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane spnFunction;
    private javax.swing.JScrollPane spnFunctionRole;
    private javax.swing.JTable tblFunction;
    private javax.swing.JTable tblFunctionRole;
    // End of variables declaration//GEN-END:variables
}
